unfinished

diff --git a/etc/system_perf.yml b/etc/system_perf.yml
--- a/etc/system_perf.yml
+++ b/etc/system_perf.yml
@@ -1,6 +1,356 @@
 stepback: false
 command_type: system
 
+variables:
+  ###
+  # Leave this section uncommented to enable compile.
+  _real_compile_amazon2: &_compile_amazon2
+      - name: compile
+        variant: compile-amazon2
+      - name: genny_generate_all_tasks
+        variant: compile-amazon2
+  _real_compile_rhel70: &_compile_rhel70
+      - name: compile
+        variant: compile-rhel70
+      - name: genny_generate_all_tasks
+        variant: compile-amazon2
+  _real_expansions: &_expansion_updates
+    []
+  ###
+
+###
+# **Or**: Leave this section uncommented to bypass/skip compile.
+#  _skip_compile_amazon2: &_compile_amazon2
+#      - name: genny_generate_all_tasks
+#        variant: compile-amazon2
+#  _skip_compile_rhel70: &_compile_rhel70
+#      - name: genny_generate_all_tasks
+#        variant: compile-amazon2
+#  _skip_expansions: &_expansion_updates
+#      # This is the normal (amazon2) "compile" artifact from https://evergreen.mongodb.com/version/sys_perf_4.4_78207ca380688c73b1a217f23d5b7c8803bef9cd
+#      - key: mdb_binary_for_client
+#        value: https://dsi-donot-remove.s3-us-west-2.amazonaws.com/compile_artifacts/mongodb-sys_perf_4.4_78207ca380688c73b1a217f23d5b7c8803bef9cd.tar.gz
+#      - key: mdb_binary_for_server
+#        value: https://dsi-donot-remove.s3-us-west-2.amazonaws.com/compile_artifacts/mongodb-sys_perf_4.4_78207ca380688c73b1a217f23d5b7c8803bef9cd.tar.gz
+###
+
+  _src_dir: &src_dir src/mongo
+  _modules: &modules
+    - dsi
+    - genny
+    - signal-processing
+    - workloads
+    - linkbench
+    - linkbench2
+    - mongo-perf
+    - YCSB
+    - benchmarks
+    - py-tpcc
+
+modules:
+###
+# Same in every DSI project
+- name: dsi
+  repo: git@github.com:10gen/dsi.git
+  prefix: ../../src
+  branch: master
+- name: genny
+  repo: git@github.com:10gen/genny.git
+  prefix: ../../src
+  branch: master
+- name: signal-processing
+  repo: git@github.com:10gen/signal-processing.git
+  prefix: ../../src
+  branch: master
+- name: workloads
+  repo: git@github.com:10gen/workloads.git
+  prefix: ../../src
+  branch: master
+- name: linkbench
+  repo: git@github.com:10gen/linkbench.git
+  prefix: ../../src
+  branch: master
+- name: linkbench2
+  repo: git@github.com:10gen/linkbench2.git
+  prefix: ../../src
+  branch: master
+- name: mongo-perf
+  repo: git@github.com:mongodb/mongo-perf.git
+  prefix: ../../src
+  branch: master
+- name: YCSB
+  repo: git@github.com:mongodb-labs/YCSB.git
+  prefix: ../../src
+  branch: master
+  ref: 4e7287880c04514cad2df5761b9511c940a33059
+- name: benchmarks
+  repo: git@github.com:mongodb-labs/benchmarks.git
+  prefix: ../../src
+  branch: master
+- name: py-tpcc
+  repo: git@github.com:mongodb-labs/py-tpcc.git
+  prefix: ../../src
+  branch: master
+  ref: 2d19705337a40e24831a904266a648b85df5be84
+
+
+###
+# Same in every DSI project
+pre:
+    - func: "f_other_pre_ops"
+    - func: "f_dsi_pre_run"
+post:
+    - func: "f_dsi_post_run"
+    - func: "f_other_post_ops"
+###
+
+
+functions:
+  ###
+  # Same in every DSI project
+  "f_dsi_pre_run":
+    - command: manifest.load
+    - command: expansions.update
+      params:
+        updates: *_expansion_updates
+  "f_run_dsi_workload":
+    - command: shell.exec
+      params:
+        script: |
+          rm -rf ./*
+          mkdir src
+    - command: manifest.load
+    - command: git.get_project
+      params:
+        directory: *src_dir
+        revisions: &revisions_list
+          dsi: ${dsi_rev}
+          genny: ${genny_rev}
+          signal-processing: ${signal-processing_rev}
+          linkbench: ${linkbench_rev}
+          linkbench2: ${linkbench2_rev}
+          workloads: ${workloads_rev}
+          mongo-perf: ${mongo-perf_rev}
+          YCSB: ${YCSB_rev}
+          benchmarks: ${benchmarks_rev}
+          py-tpcc: ${py-tpcc_rev}
+    - command: expansions.write
+      params:
+        file: ./expansions.yml
+    - command: shell.exec
+      params:
+        continue_on_err: true
+        script: ./src/dsi/run-dsi run_workload
+    - command: shell.exec
+      type: system
+      params:
+        script: ./src/dsi/run-dsi determine_failure -m SYSTEM
+    - command: shell.exec
+      type: setup
+      params:
+        script: ./src/dsi/run-dsi determine_failure -m SETUP
+    - command: shell.exec
+      type: test
+      params:
+        script: ./src/dsi/run-dsi determine_failure -m TEST
+    - command: shell.exec
+      type: test
+      params:
+        script: |
+          ./src/dsi/run-dsi analysis
+          # detect outliers needs to run, so defer the post_run_check exit status to later
+          echo $? > post_run_check.status
+    - command: json.send
+      params:
+        name: "perf"
+        file: "./build/LegacyPerfJson/perf.json"
+    - command: shell.exec
+      params:
+        script: |
+          set -o errexit
+          is_patch=${is_patch}
+          task_id=${task_id}
+          perf_jira_user=${perf_jira_user}
+          perf_jira_pw=${perf_jira_pw}
+          analysis_user=${dsi_analysis_atlas_user}
+          analysis_password=${dsi_analysis_atlas_pw}
+          evergreen_api_key=${evergreen_api_key}
+          evergreen_api_user=${evergreen_api_user}
+          source ./src/dsi/src/signal_processing_setup.sh
+    - command: shell.exec
+      params:
+        script: |
+          set -o verbose
+          source ./signal_processing_venv/bin/activate
+          detect-changes --config .signal-processing.yml --mongo-repo=./src/mongo
+    - command: shell.exec
+      type: test
+      params:
+        script: |
+          set -o verbose
+          exit $(cat post_run_check.status)
+  "f_dsi_post_run":
+      - command: shell.exec
+        params:
+          script: ./src/dsi/run-dsi infrastructure_teardown
+      - command: shell.exec
+        params:
+          script: ./src/dsi/run-dsi ./src/dsi/src/dsi/make_artifact.sh
+      - command: s3.put
+        params:
+          aws_key: ${aws_key}
+          aws_secret: ${aws_secret}
+          local_file: dsi-artifacts.tgz
+          remote_file: ${project_dir}/${build_variant}/${revision}/${task_id}/${version_id}/logs/dsi-artifacts-${task_name}-${build_id}-${execution}.${ext|tgz}
+          bucket: mciuploads
+          permissions: public-read
+          content_type: ${content_type|application/x-gzip}
+          display_name: Dsi Artifacts - Execution ${execution}
+      - command: s3.put
+        params:
+          aws_key: ${aws_key}
+          aws_secret: ${aws_secret}
+          local_file: src/mongo/workloads/workloads/jsdoc/jsdocs-redirect.html
+          remote_file: ${project_dir}/${build_variant}/${revision}/${task_id}/${version_id}/logs/workloads-${task_name}-${build_id}.html
+          bucket: mciuploads
+          permissions: public-read
+          content_type: text/html
+          display_name: workloads documentation
+      - command: attach.results
+        params:
+          file_location: report.json
+      - command: json.send
+        params:
+          name: "perf"
+          file: "./build/LegacyPerfJson/perf.json"
+      - command: s3.put
+        params:
+          aws_key: ${aws_key}
+          aws_secret: ${aws_secret}
+          local_file: pip-requirements.txt
+          remote_file: ${project}/${build_variant}/${revision}/pip-requirements-${task_id}-${execution}.txt
+          bucket: mciuploads
+          permissions: public-read
+          content_type: atext-plain
+          display_name: Pip Requirements
+  ###
+
+
+  "f_other_post_ops":
+      - command: shell.exec
+        params:
+          working_dir: src
+          script: |
+            # removes files from the (local) scons cache when it's over a
+            # threshold, to the $prune_ratio percentage. Ideally override
+            # these default values in the distro config in evergreen.
+            if [ -d "${scons_cache_path}" ]; then
+                /opt/mongodbtoolchain/v3/bin/python3 buildscripts/scons_cache_prune.py --cache-dir ${scons_cache_path} --cache-size ${scons_cache_size|200} --prune-ratio ${scons_prune_ratio|0.8}
+            fi
+  "f_other_pre_ops":
+    - &f_other_pre_ops
+      command: shell.exec
+      params:
+        silent: true
+        script: |
+          for PS in mongo{,d,s,import,export,dump,restore,stat,files,top,bridge} resmoke.py python{,2} lldb _test; do
+              pkill -9 "$PS"
+          done
+
+  ###
+  # Compile
+  "compile mongodb":
+    - command: shell.exec
+      params:
+        working_dir: src
+        script: |
+          set -o errexit
+          set -o verbose
+
+          # We get the raw version string (r1.2.3-45-gabcdef) from git
+          MONGO_VERSION=$(git describe)
+          # If we're going to compile the upstream wtdevelop repository for wiredtiger, add
+          # that githash to version string.
+          if [ "${wtdevelop|}" = "-wtdevelop" ]; then
+            WT_VERSION=$(cd src/third_party/wtdevelop; git describe | cut -c 9-)
+            MONGO_VERSION="$MONGO_VERSION-wtdevelop-$WT_VERSION"
+          fi
+          # If this is a patch build, we add the patch version id to the version string so we know
+          # this build was a patch, and which evergreen task it came from
+          if [ "${is_patch|}" = "true" ]; then
+            MONGO_VERSION="$MONGO_VERSION-patch-${version_id}"
+          fi
+
+          # This script converts the generated version string into a sanitized version string for
+          # use by scons and uploading artifacts as well as information about for the scons cache.
+          MONGO_VERSION=$MONGO_VERSION USE_SCONS_CACHE=${use_scons_cache|false} ${python|/opt/mongodbtoolchain/v2/bin/python2} buildscripts/generate_compile_expansions.py --out compile_expansions.yml
+    # Then we load the generated version data into the agent so we can use it in task definitions
+    - command: expansions.update
+      params:
+        file: src/compile_expansions.yml
+    - command: shell.exec
+      params:
+        working_dir: src/src/mongo/gotools/src/github.com/mongodb/mongo-tools
+        script: |
+          set -o verbose
+          set -o errexit
+          # make sure newlines in the scripts are handled correctly by windows
+          if [ "Windows_NT" = "$OS" ]; then
+            set -o igncr
+          fi;
+          # set_goenv provides set_goenv(), print_ldflags() and print_tags() used below
+          . ./set_goenv.sh
+          GOROOT="" set_goenv || exit
+          go version
+          build_tools="bsondump mongostat mongofiles mongoexport mongoimport mongorestore mongodump mongotop"
+          if [ "${build_mongoreplay}" = "true" ]; then
+              build_tools="$build_tools mongoreplay"
+          fi
+          for i in $build_tools; do
+              go build -ldflags "$(print_ldflags)" ${args} -tags "$(print_tags ${tooltags})" -o "../../../../../../mongo-tools/$i${exe|}" $i/main/$i.go
+              "../../../../../../mongo-tools/$i${exe|}" --version
+          done
+    - command: shell.exec
+      params:
+        working_dir: src
+        script: |
+          set -o errexit
+          set -o verbose
+          ${python|/opt/mongodbtoolchain/v2/bin/python2} ./buildscripts/scons.py ${compile_flags|} ${scons_cache_args|} mongo${extension} --use-new-tools mongod${extension} mongos${extension} MONGO_VERSION=${version}
+          mkdir -p mongodb/bin
+          mkdir -p mongodb/jstests/hooks
+          mv mongo${extension|} mongodb/bin
+          mv mongod${extension|} mongodb/bin
+          mv mongos${extension|} mongodb/bin
+          mv src/mongo-tools/* mongodb/bin
+          if [ -d jstests/hooks ]
+          then
+            echo "Fetching JS test DB correctness checks from directory jstests"
+            cp -a jstests/* mongodb/jstests
+
+            echo "Now adding our own special run_validate_collections.js wrapper"
+            mv mongodb/jstests/hooks/run_validate_collections.js mongodb/jstests/hooks/run_validate_collections.actual.js
+
+            cat << EOF > mongodb/jstests/hooks/run_validate_collections.js
+            print("NOTE: run_validate_collections.js will skip the oplog!");
+            TestData = { skipValidationNamespaces: ['local.oplog.rs'] };
+            load('jstests/hooks/run_validate_collections.actual.js');
+          EOF
+          fi
+          tar czf mongodb${wtdevelop|}.tar.gz mongodb
+    - command: s3.put
+      params:
+        aws_key: ${aws_key}
+        aws_secret: ${aws_secret}
+        local_file: src/mongodb${wtdevelop|}.tar.gz
+        remote_file: ${project_dir}/${version_id}/${revision}/${platform}/mongodb${wtdevelop|}-${version_id}.tar.gz
+        bucket: mciuploads
+        permissions: public-read
+        content_type: ${content_type|application/x-gzip}
+        display_name: mongodb${wtdevelop|}.tar.gz
+
+
+
 pre:
 
 post:
@@ -576,28 +926,6 @@ tasks:
     - func: "run test"
     - func: "analyze"
 
-
-#######################################
-#               Modules               #
-#######################################
-# if a module is added and to be added to the manifest
-# be sure to add the module to git.get_project revisions parameter
-modules:
-- name: dsi
-  repo: git@github.com:10gen/dsi.git
-  prefix: dsi
-  branch: legacy
-
-- name: workloads
-  repo: git@github.com:10gen/workloads.git
-  prefix: workloads
-  branch: master
-
-
-- name: signal-processing
-  repo: git@github.com:10gen/signal-processing.git
-  prefix: signal_processing
-  branch: master
 
 #######################################
 #         Buildvariants               #
